import { Timestamp } from 'firebase/firestore';

// Define a type for server timestamp format
export interface ServerTimestamp {
  seconds: number;
  nanoseconds: number;
}

// Define a generic timestamp type to support multiple formats
export type AppTimestamp = Date | Timestamp | ServerTimestamp;

/**
 * Chord representation
 */
export interface Chord {
  name: string;
  notation: string;
  function?: string;
}

/**
 * Chord progression
 */
export interface ChordProgression {
  id: string;
  chords: Chord[] | string[];
  key: string;
  scale: string;
  mood: string;
  style: string;
  insights: string[];
  numerals?: string[];  // Roman numeral analysis of the progression
  createdAt: AppTimestamp;
  favoritedAt?: AppTimestamp;
  likes: number;
  flags: number;
  reported?: boolean;    // Indicates if the progression has been reported for low quality
  qualityScore?: number; // A score from 0-100 indicating the quality of the progression
  startingChord?: string; // The starting chord if specified in the query
  isAIGenerated?: boolean; // Indicates if the progression was generated by AI
}

/**
 * Parameters for generating a new chord progression
 */
export interface GenerationParams {
  key?: string;
  scale?: string;
  startingChord?: string;
  mood?: string;
  style?: string;
}

/**
 * Music key with display name and value
 */
export interface MusicKey {
  name: string;
  value: string;
}

/**
 * Music scale with display name and value
 */
export interface MusicScale {
  name: string;
  value: string;
}

/**
 * Music mood with display name and value
 */
export interface MusicMood {
  name: string;
  value: string;
}

/**
 * Music style with display name and value
 */
export interface MusicStyle {
  name: string;
  value: string;
}

/**
 * Report data structure
 */
export interface ReportData {
  progressionId: string;
  reason: string;
  details?: string;
  timestamp?: AppTimestamp;
}
